version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bofacustomerproddb
    volumes:
      - /data/mysql
    networks: [bofanetwork]
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
    #networks:
      #- boanetwork
  customer-app:
    image: customerapi
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 8060-8070:7070
        - "7074-7080:7074"
    networks: [bofanetwork]
    environment:
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka


      # Eureka client
      EUREKA__CLIENT__SERVICEURL: http://host.docker.internal:8761/eureka/
#      EUREKA__CLIENT__SHOULDFETCHREGISTRY: "true"
#      EUREKA__CLIENT__SHOULDREGISTERWITHEUREKA: "true"
#
#      # Override what gets registered
#      EUREKA__INSTANCE__APPNAME: customerapi
#      EUREKA__INSTANCE__HOSTNAME: customerapi    # force Eureka to use "localhost"
#      EUREKA__INSTANCE__NONSECUREPORT: "7074"      # advertise the HOST port
#      EUREKA__INSTANCE__PREFERIPADDRESS: "false"
#      # make it unique if you scale
#      EUREKA__INSTANCE__INSTANCEID: "customerapi-localhost:7074"
#
#      # optional but recommended so Eureka health links work from host:
#      EUREKA__INSTANCE__STATUSPAGEURL: "http://localhost:7074health"
#      EUREKA__INSTANCE__HEALTHCHECKURL: "http://localhost:7074/health"

    volumes:
      - /data/compose-app
    #networks:
      #- boanetwork   
    

### put all the networks here
#networks:
  #boanetwork:
networks:
  bofanetwork:
    external: true

  